# Generated by Django 4.2.4 on 2023-10-03 21:49

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Web Design", max_length=60)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        default="portfolio/default.jpg",
                        upload_to="portfolio/",
                        validators=[portfolio.models.Portfolio.validate_image],
                    ),
                ),
                ("description", ckeditor_uploader.fields.RichTextUploadingField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.portfoliocategory",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_date",),
            },
        ),
    ]
