# Generated by Django 4.2.4 on 2023-10-03 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_portfolio_client_portfolio_project_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="project_date",
            field=models.DateTimeField(default=datetime.date(2023, 10, 4)),
        ),
    ]
