# Generated by Django 4.2.4 on 2023-10-04 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_rename_image_portfolio_image1_portfolio_image2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="project_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 23, 32, 51, 791681)
            ),
        ),
    ]
