# Generated by Django 4.2.4 on 2023-10-04 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0008_alter_portfolio_project_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="project_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 4, 23, 45, 31, 419505)
            ),
        ),
    ]
