# Generated by Django 4.2.4 on 2023-10-12 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0010_alter_portfolio_project_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="project_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 12, 15, 11, 24, 82110)
            ),
        ),
    ]
