# Generated by Django 4.2.4 on 2023-10-15 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0036_alter_portfolio_project_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="project_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 15, 23, 38, 49, 467649)
            ),
        ),
    ]
