# Generated by Django 4.2.4 on 2023-10-02 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_image'),
        ('blog', '0002_post_counted_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='login_require',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile'),
        ),
    ]
