# Generated by Django 4.2.4 on 2023-10-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_remove_post_login_require_alter_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="estimated_time",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
