# Generated by Django 4.2.4 on 2023-10-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_estimated_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="estimated_time",
            field=models.PositiveIntegerField(
                default=10, verbose_name="Estimated time (minutes)"
            ),
        ),
    ]
